apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
  labels:
    app: my-nextjs-app
spec:
  replicas: 2   # run 2 pods for reliability
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      containers:
        - name: my-nextjs-app
          image: ghcr.io/kasulapavankumar-cloud/my-nextjs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
              
